# Generated by Django 4.1.2 on 2022-10-16 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
